server:
  tomcat:
    uri-enconding: UTF-8
  port: 8080
  compression:
    enabled: true

spring:
  profiles:
    active: production
  jackson:
    serialization:
      indent_output: true
  application:
    name: employee
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb/${MONGO_DATABASE}
      
logging:
  config: classpath:logback.xml